#LIB_DEPENDS+= libelf.so:${PORTSDIR}/devel/libelf
#CFLAGS+= -I${LOCALBASE}/include/libelf

# zrj: not sure how it got into llvm/clover
CXXFLAGS+= -fexceptions

# workaround for dri compilation when vaapi.pc is available (has build dep on v4l_compat)
CONFIGURE_ARGS+= --disable-va
